server:
  port: 8080
  servlet:
    context-path: /springboot-2.2.4

logging:
  level:
    root: ${LOG_LEVEL:INFO}
  file:
    name: springboot-2.2.4.log

spring:
  application:
    name: springboot-2.2.4
